// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { DEMO_MODE } from '@/lib/demoMode';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * DEMO SUPABASE STUB
 * ------------------
 * The demo build never talks to a real Supabase project. Instead of threading
 * DEMO_MODE through every collaboration feature (comments, notifications,
 * activity feed, realtime channels), we hand back an inert client whose query
 * builder resolves to empty results and whose realtime + auth methods are
 * no-ops. Every component keeps rendering its normal empty state and no
 * network request or websocket is ever opened.
 */
function createDemoStub() {
  const emptyList = { data: [], error: null, count: 0 };
  const emptyOne = { data: null, error: null };

  const makeBuilder = (): unknown => {
    const builder: Record<string, unknown> = {};
    const passthrough = [
      'select', 'insert', 'update', 'upsert', 'delete', 'eq', 'neq', 'in',
      'is', 'not', 'or', 'and', 'gte', 'lte', 'gt', 'lt', 'like', 'ilike',
      'contains', 'containedBy', 'match', 'filter', 'order', 'limit', 'range',
      'returns', 'overlaps', 'textSearch', 'abortSignal', 'csv', 'geojson',
    ];
    for (const m of passthrough) builder[m] = () => builder;
    builder.single = () => Promise.resolve(emptyOne);
    builder.maybeSingle = () => Promise.resolve(emptyOne);
    // Make the builder awaitable (resolves to an empty list result).
    builder.then = (resolve: (v: unknown) => unknown) => resolve(emptyList);
    return builder;
  };

  const channelStub: Record<string, unknown> = {
    on: () => channelStub,
    subscribe: (cb?: (status: string) => void) => {
      if (cb) cb('SUBSCRIBED');
      return channelStub;
    },
    unsubscribe: () => Promise.resolve('ok'),
    track: async () => 'ok',
    untrack: async () => 'ok',
    send: async () => 'ok',
    presenceState: () => ({}),
  };

  const authStub = {
    getUser: async () => ({ data: { user: null }, error: null }),
    getSession: async () => ({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe() {} } } }),
    signInWithPassword: async () => ({ data: { user: null, session: null }, error: { message: 'Demo mode' } }),
    signUp: async () => ({ data: { user: null, session: null }, error: null }),
    signOut: async () => ({ error: null }),
    resetPasswordForEmail: async () => ({ data: {}, error: null }),
    updateUser: async () => ({ data: { user: null }, error: null }),
    setSession: async () => ({ data: { session: null }, error: null }),
    exchangeCodeForSession: async () => ({ data: { session: null }, error: null }),
    getUserIdentities: async () => ({ data: { identities: [] }, error: null }),
  };

  return {
    from: () => makeBuilder(),
    rpc: () => Promise.resolve({ data: null, error: null }),
    channel: () => channelStub,
    removeChannel: () => Promise.resolve('ok'),
    getChannels: () => [],
    auth: authStub,
    functions: { invoke: async () => ({ data: null, error: null }) },
    storage: { from: () => ({ upload: async () => ({ data: null, error: null }), getPublicUrl: () => ({ data: { publicUrl: '' } }) }) },
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabase: any = DEMO_MODE
  ? createDemoStub()
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: brokeredPreviewStorage(),
        persistSession: true,
        autoRefreshToken: true,
      },
    });
